# Generated by Django 4.2.9 on 2024-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='code_postal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
