# Generated by Django 4.2.9 on 2024-01-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_is_doctor'),
        ('users', '0010_alter_reste_token_email'),
    ]

    operations = [
    ]
