# Generated by Django 4.2.9 on 2024-01-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20240109_1707'),
        ('users', '0011_merge_20240109_1926'),
    ]

    operations = [
    ]
