# Generated by Django 5.0.1 on 2024-01-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.specialty'),
        ),
    ]
